In [2]:
import pandas as pd
import numpy as np

In [231]:
data1 = [10, 20, 30, 40, 50]

In [97]:
x_min=min(data1)
x_max=max(data1)

In [98]:
scaled=[(X-x_min)/(x_max-x_min) for X in data1]

In [99]:
print(scaled)

[0.0, 0.25, 0.5, 0.75, 1.0]


In [221]:
import pandas as pd

df = pd.DataFrame({'A': [10, 20, 30, 40]})

# Add 5 to each element in column 'A'
df['A_plus_5'] = [x + 5 for x in df['A']]
df

A  A_plus_5
0  10        15
1  20        25
2  30        35
3  40        45

In [224]:
s=zip(df['A'], df['B'])

In [222]:
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30]
})

# Add A and B for each row
df['sub'] = [b - a for a, b in zip(df['A'], df['B'])]
print(df)

   A   B  sub
0  1  10    9
1  2  20   18
2  3  30   27


In [227]:
df['Flag'] = ['High' if x > 2 else 'Low' for x in df['A']]

In [228]:
df

A   B  sub  Flag
0  1  10    9   Low
1  2  20   18   Low
2  3  30   27  High

In [229]:
df.groupby('Flag')['B'].mean()

Flag
High    30.0
Low     15.0
Name: B, dtype: float64

In [232]:
df2=pd.DataFrame(data1)

In [233]:
data2=np.array(data1)

In [234]:
data2.shape

(5,)

In [235]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

In [118]:
data = np.array([[10], [20], [30], [40], [50]])
data

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [124]:
data.shape

(5, 1)

In [ ]:
da_arr= np.array(data)

In [121]:
type(data)

numpy.ndarray

In [ ]:
scaler.fit_transform(data).flatten()

[0.0, 0.25, 0.5, 0.75, 1.0]

In [236]:
scaled2=scaled1.flatten().tolist()

NameError: name 'scaled1' is not defined

In [46]:
scaled2

[0.0, 0.25, 0.5, 0.75, 1.0]

In [237]:
scaled=scaler.fit_transform(df)

ValueError: could not convert string to float: 'Low'

In [25]:
scaled

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [26]:
# Get 1D list directly
scaled_1d = scaled.flatten().tolist()

In [27]:
scaled_1d

[0.0, 0.25, 0.5, 0.75, 1.0]

In [29]:
lst_2d=scaled.tolist()
lst_2d

[[0.0], [0.25], [0.5], [0.75], [1.0]]

In [12]:
df = pd.DataFrame({"Car": ["Honda", "Honda", "Toyota", "Toyota", "Ford", "Ford", "Ford"], "Category": ["Sedan", "SUV", "Sedan", "SUV", "Sedan", "Pickup", "Pickup"],"Price": [25000, 30000, 23000, 28000, 24000, 35000, 36000], "Units Sold": [120, 100, 150, 90, 110, 80, 90]})

In [240]:

data = {
    "Product": ["Pen", "Book", "Laptop", "Phone", "Bag", "Shoes", "Book", "Pen", "Laptop"],
    "Price":   [20, 150, 60000, 30000, 1200, 2500, 150, 20, 60000],
    "Quantity":[10, 5, 2, 1, 3, 2, 7, 15, 1],
    "Region":  ["North", "South", "West", "East", "North", "South", "East", "West", "North"]
}


In [241]:

df = pd.DataFrame(data)

In [242]:
df

Product  Price  Quantity Region
0     Pen     20        10  North
1    Book    150         5  South
2  Laptop  60000         2   West
3   Phone  30000         1   East
4     Bag   1200         3  North
5   Shoes   2500         2  South
6    Book    150         7   East
7     Pen     20        15   West
8  Laptop  60000         1  North

🔥 Exercises (slightly advanced):

Create a new column Revenue = Price × Quantity.

Find the total revenue per product.

Find the top 3 products by total revenue.

Calculate the average revenue per region.

Which region sold the highest number of units overall?

In [245]:
df.groupby('Region')['Quantity'].sum()

Region
East      8
North    14
South     7
West     17
Name: Quantity, dtype: int64

In [244]:
df.groupby('Region')['Quantity'].sum().idxmax()

'West'

In [121]:
df['Product']=="Pen"

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
Name: Product, dtype: bool

In [250]:
max_pen=df[df['Product']=="Pen"].groupby('Region')['Quantity'].sum()

In [251]:
max_pen

Region
North    10
West     15
Name: Quantity, dtype: int64

In [136]:
max_units_for_pen=max_pen.max()
top_region_for_pen=max_pen.idxmax()
print(f"Maxmium pen sold region is {top_region_for_pen} with {max_units_for_pen} units")

Maxmium pen sold region is West with 15 units


In [89]:
df['Revenue']=df['Price']*df['Quantity']

In [ ]:
df.isnull().sum()

Product     0
Price       0
Quantity    0
Region      0
Revenue     0
dtype: int64

In [94]:
df['Revenue'].isnull().sum()

np.int64(0)

In [106]:
int(df['Price'].sum())

154040

In [ ]:
df.groupby('Product')['Price'].sum()

Product
Bag         1200
Book         300
Laptop    120000
Pen           40
Phone      30000
Shoes       2500
Name: Price, dtype: int64

In [110]:
df.nlargest(3,'Revenue')

Product  Price  Quantity Region  Revenue
2  Laptop  60000         2   West   120000
8  Laptop  60000         1  North    60000
3   Phone  30000         1   East    30000

In [113]:
df.groupby('Region')['Revenue'].mean().round(1)

Region
East     15525.0
North    21266.7
South     2875.0
West     60150.0
Name: Revenue, dtype: float64

Exercises:

Print all products with Price > 2000.

Print only the Product names where Stock < 20.

Create a new column TotalValue = Price * Stock.

Find the most expensive product (max Price).

Sort the DataFrame by Price in descending orde

In [87]:
df[df['Price']>2000]

Product  Price  Quantity Region
2  Laptop  60000         2   West
3   Phone  30000         1   East
5   Shoes   2500         2  South
8  Laptop  60000         1  North

In [88]:
df.loc[df['Stock']<20,'Stock']

KeyError: 'Stock'

In [49]:
df['TotalValue']=df['Price']*df['Stock']

In [70]:
most_expensive=df.loc[[df['Price'].idxmax()]]

In [67]:
df['Price'].max()

np.int64(60000)

In [218]:
most_expensive=df.nlargest(1,'Price')

KeyError: 'Price'

In [ ]:
most_expensive

Product  Price  Stock  TotalValue
2  Laptop  60000     10      600000
3   Phone  30000     15      450000
5   Shoes   2500     25       62500
4     Bag   1200     30       36000
1    Book    150     50        7500
0     Pen     20    100        2000

In [83]:
df.sort_values(by=["Price", "Stock"],ascending=False)

Product  Price  Stock  TotalValue
2  Laptop  60000     10      600000
3   Phone  30000     15      450000
5   Shoes   2500     25       62500
4     Bag   1200     30       36000
1    Book    150     50        7500
0     Pen     20    100        2000

In [26]:
data = [4, 5, 2, 4, 5, 7, 2, 9]
unique_values = list(dict.fromkeys(data))

In [10]:
set(data)

{2, 4, 5, 7, 9}

In [27]:
lst=[]

for i in data:
    if i not in lst:
        lst.append(i)

In [28]:
lst

[4, 5, 2, 7, 9]

In [137]:
data = {
    "Product": ["Pen", "Book", "Laptop", "Phone", "Bag", "Shoes", "Book", "Pen", "Laptop", "Phone"],
    "Price":   [20, 150, 60000, 30000, 1200, 2500, 150, 20, 60000, 30000],
    "Quantity":[10, 5, 2, 1, 3, 2, 7, 15, 1, 5],
    "Region":  ["North", "South", "West", "East", "North", "South", "East", "West", "North", "South"]
}

In [162]:
df=pd.DataFrame(data)

In [139]:
df

Product  Price  Quantity Region
0     Pen     20        10  North
1    Book    150         5  South
2  Laptop  60000         2   West
3   Phone  30000         1   East
4     Bag   1200         3  North
5   Shoes   2500         2  South
6    Book    150         7   East
7     Pen     20        15   West
8  Laptop  60000         1  North
9   Phone  30000         5  South

Advanced Python/Pandas Interview Tasks

Dynamic Ranking:
Rank products within each region by revenue and add a column Rank (1 = highest revenue).

Outlier Detection:
Identify products whose revenue is more than 2 standard deviations above the mean revenue.

Rolling Calculations:
If your DataFrame had a Date column for sales, calculate a 7-day rolling sum of revenue per product.

Top N per Group:
For each region, show top 3 products by quantity sold, including all relevant columns.

Conditional Aggregation:
Calculate total revenue per region only for products priced above 1000.

Multi-level Indexing:
Create a multi-index DataFrame with Region and Product as indices and show revenue, quantity, and average price.

Percentage Contribution:
For each region, calculate each product’s percentage contribution to total region revenue.

Pivot Table with Aggregation:
Pivot table showing sum, mean, and max revenue per product across regions.

Sparse Filtering:
Identify products that are sold in only 1 or 2 regions.

Custom Function Aggregation:
Apply a custom function (like weighted revenue score: Revenue * log(Quantity+1)) grouped by product or region.

Cumulative Share Analysis:
Sort products by revenue and calculate cumulative percentage share, to identify the top contributors (Pareto 80/20 rule).

Data Quality Check:
Detect duplicate rows, missing values, or inconsistent prices for the same product across regions.

In [163]:
df['Revenue']=df['Price']*df['Quantity']

In [164]:
df

Product  Price  Quantity Region  Revenue
0     Pen     20        10  North      200
1    Book    150         5  South      750
2  Laptop  60000         2   West   120000
3   Phone  30000         1   East    30000
4     Bag   1200         3  North     3600
5   Shoes   2500         2  South     5000
6    Book    150         7   East     1050
7     Pen     20        15   West      300
8  Laptop  60000         1  North    60000
9   Phone  30000         5  South   150000

In [166]:
df['Rank']=df.groupby('Region')['Revenue'].rank(method='dense',ascending=False)

In [167]:
df

Product  Price  Quantity Region  Revenue  Rank
0     Pen     20        10  North      200   3.0
1    Book    150         5  South      750   3.0
2  Laptop  60000         2   West   120000   1.0
3   Phone  30000         1   East    30000   1.0
4     Bag   1200         3  North     3600   2.0
5   Shoes   2500         2  South     5000   2.0
6    Book    150         7   East     1050   2.0
7     Pen     20        15   West      300   2.0
8  Laptop  60000         1  North    60000   1.0
9   Phone  30000         5  South   150000   1.0

In [168]:
df.sort_values(by=['Region','Rank'],ascending=[True,True])

Product  Price  Quantity Region  Revenue  Rank
3   Phone  30000         1   East    30000   1.0
6    Book    150         7   East     1050   2.0
8  Laptop  60000         1  North    60000   1.0
4     Bag   1200         3  North     3600   2.0
0     Pen     20        10  North      200   3.0
9   Phone  30000         5  South   150000   1.0
5   Shoes   2500         2  South     5000   2.0
1    Book    150         5  South      750   3.0
2  Laptop  60000         2   West   120000   1.0
7     Pen     20        15   West      300   2.0

In [169]:
df1 = df[df['Rank']==1].sort_values(["Region", "Rank"])
df1

Product  Price  Quantity Region  Revenue  Rank
3   Phone  30000         1   East    30000   1.0
8  Laptop  60000         1  North    60000   1.0
9   Phone  30000         5  South   150000   1.0
2  Laptop  60000         2   West   120000   1.0

In [173]:
df = df[df['Rank']<=2].sort_values(["Region", "Rank"])

In [174]:
df

Product  Price  Quantity Region  Revenue  Rank
3   Phone  30000         1   East    30000   1.0
6    Book    150         7   East     1050   2.0
8  Laptop  60000         1  North    60000   1.0
4     Bag   1200         3  North     3600   2.0
9   Phone  30000         5  South   150000   1.0
5   Shoes   2500         2  South     5000   2.0
2  Laptop  60000         2   West   120000   1.0
7     Pen     20        15   West      300   2.0

In [2]:
s="adarsh"

In [31]:
s[::-1]

'hsrada'

In [32]:
type(s)

str

In [28]:
rev = "".join(reversed(s))
print(rev)   

hsrada


In [60]:
rev=""

for i in range(len(s)):
    print(i)

0
1
2
3
4
5


In [67]:
rev2="".join(reversed(s))

In [68]:
rev2

'hsrada'

In [70]:
s="hello"
rev=""
for i in s:
    rev=i+rev
print(rev)
    

olleh


In [ ]:
s=input("Enter text")
s=s.lower()
if s==s[::-1]:
    print("Text is Plaindrome")
else:
    print("Text is Not a palindrome")

Text is Plaindrome


In [82]:
s="Madam"
s=s.lower()
rev=""
for i in s:
    rev=i+rev
if s==rev:
    print('palindrome')
else:
    print("Not palindrome")


palindrome


In [88]:
s='madam'
i,j=0,len(s)-1
is_palindrome= True
while(i<j):
    if s[i] != s[j]:
        is_palindrome=False
        break
    i+=1
    j-=1
print("Polindrome" if is_palindrome else "Not a polindrom" )

Polindrome


In [2]:
s="Hello world"
freq={}
for i in s:
    if i in freq:
        freq[i]+=1
    else:
        freq[i]=1
print(freq)

    


{'H': 1, 'e': 1, 'l': 3, 'o': 2, ' ': 1, 'w': 1, 'r': 1, 'd': 1}


In [3]:
from collections import Counter

In [7]:
from collections import Counter

s = "hello world"
freq = Counter(s)
print(freq)


Counter({'l': 3, 'o': 2, 'h': 1, 'e': 1, ' ': 1, 'w': 1, 'r': 1, 'd': 1})


In [15]:
s = "hello world"
for i in set(s):
    print(f"{i}: {s.count(i)}")

l: 3
 : 1
o: 2
d: 1
r: 1
e: 1
h: 1
w: 1


In [23]:
def factorical_itr(n):
    fact=1
    for i in range(1,n+1):
        fact*=i
    return fact
print(factorical_itr(5))


120


In [64]:
def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i ==0:
            return False
    return True
def prime_lst(n):
    prime=[]
    for i in range(2,n+1):
        if is_prime(i):
            prime.append(i)
    return prime
num=int(input("Enter a number:"))
print(num,"is prime" if is_prime(num) else "is not prime")
print(f"all prime num upto {num}:",prime_lst(num))



13 is prime
all prime num upto 13: [2, 3, 5, 7, 11, 13]


In [50]:
stack=[]
stack.append(10)
stack.append(20)
stack.append(30)

In [47]:
stack

[10, 20]

In [46]:
stack.pop()

30

In [51]:
top=stack[-1]

In [52]:
top

30

In [54]:
lst=[]
lst.append(10)
lst.append(20)
lst.append(30)

In [56]:
lst.pop()

30

In [58]:
lst[-1]

20

In [65]:
import numpy as np

In [ ]:
arr=np.random.randint(1,1000,size=(5,5))

In [85]:
arr[arr%2==0]=0
print("after imputing\n",arr)

after imputing
 [[  0 291   0   0 485]
 [  0   0   0 473 179]
 [  0 535   0   0   0]
 [  0   0   0 435 147]
 [455 753 333   0   0]]


In [94]:
arr=np.random.randint(1,1000,size=5).tolist()

In [107]:
import pandas as pd

data = {
    'A': [1,  2,3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)


Original DataFrame:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


In [99]:
int(df['B'].mean())

5

In [100]:
df.shape

(3, 3)

In [143]:
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, None, 4],
    'B': [5, np.nan, 7, 8],
    'C': ['apple', 'banana', 'banana', 'apple']
}

df = pd.DataFrame(data)
print(df)


     A    B       C
0  1.0  5.0   apple
1  2.0  NaN  banana
2  NaN  7.0  banana
3  4.0  8.0   apple


In [144]:
df["B"]=df["B"].fillna(df["B"].mean().round(2))

In [145]:
df

A     B       C
0  1.0  5.00   apple
1  2.0  6.67  banana
2  NaN  7.00  banana
3  4.0  8.00   apple

In [146]:
# Fill NaN in column 'C' with mode
df['C'] = df['C'].fillna(df['C'].mode()[0])

In [147]:
df

A     B       C
0  1.0  5.00   apple
1  2.0  6.67  banana
2  NaN  7.00  banana
3  4.0  8.00   apple

In [149]:

print(df['C'].mode()[0])  


apple


In [150]:
df['A']=df['A'].fillna(10)

In [ ]:
df

A     B       C
0   1.0  5.00   apple
1   2.0  6.67  banana
2  10.0  7.00  banana
3   4.0  8.00   apple

In [152]:
# Sample DataFrame
np.random.seed(0)
df = pd.DataFrame({
    'A': np.random.randint(1, 100, 10),
    'B': np.random.randint(1, 100, 10)
})


In [153]:
df

A   B
0  45  71
1  48  89
2  65  89
3  68  13
4  68  59
5  10  66
6  84  40
7  22  88
8  37  47
9  88  89

In [175]:
q50 = df['A'].quantile(0.5)

In [176]:
q75

np.float64(56.5)

In [ ]:
_50above=df[df["A"]>q50]

In [178]:
_75above

A   B  75above
2  65  89    False
3  68  13    False
4  68  59    False
6  84  40     True
9  88  89     True

In [179]:

# Sample DataFrames
df1 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "dept": ["HR", "IT", "Finance", "IT"],
    "salary": [40000, 50000, 60000, 45000]
})

df2 = pd.DataFrame({
    "id": [2, 3, 5],
    "dept": ["IT", "Finance", "HR"],
    "bonus": [5000, 7000, 3000]
})

In [181]:
df1

id     dept  salary
0   1       HR   40000
1   2       IT   50000
2   3  Finance   60000
3   4       IT   45000

In [182]:
df2

id     dept  bonus
0   2       IT   5000
1   3  Finance   7000
2   5       HR   3000

In [ ]:
# Merge on multiple columns
merged = pd.merge(df2, df1, on=["id", "dept"], how="right")  # outer keeps all, even non-matching rows

print(merged)

   id     dept   bonus  salary
0   1       HR     NaN   40000
1   2       IT  5000.0   50000
2   3  Finance  7000.0   60000
3   4       IT     NaN   45000


In [200]:
df1["salary"].std()

np.float64(8539.125638299665)

In [201]:
df1["salary"].var()

np.float64(72916666.66666667)

In [202]:
# Create sample DataFrame
np.random.seed(42)
df = pd.DataFrame({
    "A": np.random.randint(1, 10, 8),
    "B": np.random.randint(10, 20, 8)
})

In [ ]:
covariance = df["A"].cov(df["B"])
print("Covariance:", covariance)

Covariance: -0.875


In [206]:
correlation = df["A"].corr(df["B"])

print("Correlation:", correlation)

Correlation: -0.21418628963131547


In [208]:
print("\nCorrelation matrix:\n", df.corr())


Correlation matrix:
           A         B
A  1.000000 -0.214186
B -0.214186  1.000000


In [210]:
s=np.random.randint(1,100,6)

In [217]:
s

array([88, 30, 38,  2, 64, 60], dtype=int32)

In [213]:
h=s.tolist()

In [214]:
h

[88, 30, 38, 2, 64, 60]

In [215]:
x=np.array(h)

In [216]:
x

array([88, 30, 38,  2, 64, 60])